package com.besha.v13;

import java.util.ArrayList;

public class VitaminsList {
    private ArrayList<Vitamin> vitaminArrayList = new ArrayList<>();

    public VitaminsList() {
        Vitamin a = new Vitamin(1,"Vitamin A", "is an essential vitamin needed for growth and development, cell recognition, vision, immune function, and reproduction. it is also a powerful antioxidant and acts as a hormone in the body, affecting the expressin of genes and thereby influencing phenotype. it also helps the heart, lungs, kdneys, and other organs to function correctly.", "Adequate intakes of carotenoids from fuits and vegetables are associated with a lower risk of lung cancer. One meta-analysis suggests that some forms of vitamin A may help protect against prostate cancer. Studies in Jaban also have suggested that beta-carotene may help prevent colon cancer. Retinoic acid, a derivative of vitamin A, has been found to normalize blood sugar in mice with diabetes. Not to forget to mention than vitamin A is important in the growth of all bodily tissues, including skin and hair", "The Ready-made retinol, the active form of vitamin A, only comes from animal sources, such as organ meats, fatty fish, butter, milk, cheese, and eggs. Planet-based foods contain carotenoids, antioxidant forms of vitamin A. Carotenoid is an orange pigment that contributes to the color of certain fruits and vetgetables. such sources are pumpkin, carrots, squash, sweet potatoes and orange-colored fruits.", "excessive consumtion of vitamin A can be toxic. The toerable upper intake lever(UL) for vitamin A varies by age. The  UL is the amount above which vitamin A intake may be toxic, The NIH has established this ULS: up to 3 years UL is 600 mcg/day, 4 to 8 years 900 mcg/day, from 9 to 13 years can take up to 1700 mcg/day, while 14 to 18 years 2800 mcg per day, finaly from 19 years and over take upto 3000 mcg/day. Over consumption of vitamin A can be lead to skin changes, vision changes, brittle nails, hair changes, weak bones, vomiting, dizziness, headaches, difficulty gaining weight, irritability, fatigue, drowsiness, and liver disease in cases of extremely excessive intake.", "https://www.medicalnewstoday.com/articles/219486.php");
        Vitamin b = new Vitamin(2,"Vitamin B", "Also known as Thiamin.", "Helps break down and release energy from food, and keep the nervous system healthy.", "Thiamin is found in many types of food such as peas, fresh and dried fruit, eggs, wholegrain breads, some fortified breakfast cereals, and liver", "There's not enough evidence to know what the effects might be of taking high doses of thiamin supplements each day.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-b/");
        Vitamin b2 = new Vitamin(3,"Vitamin B2", "Also known as Riboflavin.", "Helps keep skin, eyes and the nervous system healthy, and help the body release energy from food.", "Riboflavin is found in milk, eggs, fortified breakfast cereals, and rice. UV light can destroy riboflavin, so ideally these foods should be kept out of direct sunlight.", "There's not enough evidence to know what the effects might be of taking high doses of riboflavin supplements each day.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-b/");
        Vitamin b3 = new Vitamin(4,"Vitamin B3", "Also known as Niacin.", "Helps release energy from the foods we eat and keep the nervous system and skin healthy", "There are 2 forms of niacin: nicotinic acid and nicotinamide. Both are found in food such as meat, fish, wheat flour, eggs, and milk.", "Taking high doses of nicotinic acid supplements can cause skin flushes. Taking high doses for a long time could lead to liver damage. There's not enough evidence to know what the effects might be of taking high daily doses of nicotinamide supplements.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-b/");
        Vitamin b5 = new Vitamin(5,"Vitamin B5", "Also known as Pantothenic acid.","Pantothenic acid is frequently used in combination with other B vitamins in vitamin B complex formulations. It has several functions, such as helping to release energy from food.", " it's found in almost all meats and vegetables such as chicken, beef, potatoes, tomatoes, kidney, eggs, broccoli, and wholegrains. Breakfast cereals are also a good source if they have been fortified with pantothenic acid.", "There's not enough evidence to know what the effects might be of taking high daily doses of pantothenic acid supplements.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-b/");
        Vitamin b6 = new Vitamin(6,"Vitamin B6", "Also known as pyridoxine.", "helps allow the body to use and store energy from protein and carbohydrates in food, and form haemoglobin, the substance in red blood cells that carries oxygen around the body.", "Vitamin B6 is found in a wide variety of foods like poultry, fish, bread, wholegrain cereals, eggs, vegetables, soya beans, peanuts, milk, potatoes, and some fortified breakfast cereals.", "When taking a supplement, it's important not to take too much. \n" +
                "Taking more than 200mg a day of vitamin B6 for a long time can lead to a loss of feeling in the arms and legs known as peripheral neuropathy.\n" +
                "This will usually improve once you stop taking the supplements. \n" +
                "But in a few cases when people have taken large amounts of vitamin B6, particularly for more than a few months, the effect can be permanent.\n" +
                "Taking doses of 10 to 200mg a day for short periods may not cause any harm. \n" +
                "But there's not enough evidence to say how long these doses could be taken for safely.\n" +
                "What does the Department of Health and Social Care advise?\n" +
                "You should be able to get the vitamin B6 you need by eating a varied and balanced diet. \n" +
                "If you take vitamin B6 supplements, do not take too much as this could be harmful.\n" +
                "Do not take more than 10mg of vitamin B6 a day in supplements unless advised to by a doctor.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-b/");
        Vitamin b7 = new Vitamin(7,"Vitamin B7", "Known as Biotin", "Biotin is needed in very small amounts to help the body break down fat.\n" +
                "The bacteria that live naturally in your bowel are able to make biotin, so it's not clear if you need any additional biotin from the diet.", "Biotin is also found in a wide range of foods, but only at very low levels.", "There's not enough evidence to know what the effects might be of taking high daily doses of biotin supplements.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-b/");
        Vitamin b9 = new Vitamin(8,"Vitamin B9", "known as Folate. It is a B vitamin found in many foods. The man-made form of folate is called folic acid.", "Folate helps the body form healthy red blood cells and reduce the risk of central neural tube defects, such as spina bifida, in unborn babies.", "Folate is found in small amounts in many foods including broccoli, brussels, sprouts, liver(avoid this during pregnancy), leafy grean vegetables(cabbage and spinach), peas, chickpeas, breakfast cereals fortified with folic acid", "Taking doses of folic acid higher than 1mg can mask the symptoms of vitamin B12 deficiency, which can eventually damage the nervous system if it's not spotted and treated.\n" +
                "This is particularly a concern for older people because it becomes more difficult to absorb vitamin B12 as you get older.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-b/");
        Vitamin b12 = new Vitamin(9,"Vitamin B12", "A lack of vitamin B12 could lead to vitamin B12 deficiency anaemia.", "Vitamin B12 involved in making red blood cells and keeping the nervous system healthy, releasing energy from food, and using folic acid.", "It is found in meat, salmon, cod, milk, cheese, eggs, and some fortified breakfast cereals.", "There's not enough evidence to show what the effects may be of taking high doses of vitamin B12 supplements each day.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-b/");
        Vitamin c = new Vitamin(10,"Vitamin C", "Vitamin C, also known as ascorbic acid, is a water-soluble nutrient found in some foods. In the body, it acts as an antioxidant, helping to protect cells from the damage caused by free radicals. Free radicals are compounds formed when our bodies convert the food we eat into energy. People are also exposed to free radicals in the environment from cigarette smoke, air pollution, and ultraviolet light from the sun.","Studies have shown that vitamin C may help lower blood pressure in those both with and without high blood pressure. Vitamin C is also a strong antioxidant that can strengthen your body’s natural defenses. Helps Prevent Iron Deficiencies by Improving Iron Absorption. It boosts Immunity by Helping White Blood Cells Function Better. and also protects Your Memory and Thinking as You Age", "Vitamin C is found naturally in vegetables and fruits, especially oranges and other citrus fruits. This key vitamin is also available as a natural dietary supplement in the form of vitamin C pills and vitamin C chewable tablets.", "Common side effects of vitamin C include redness and warm feeling of the skin, headache, nausea, vomiting, diarrhea, upset stomach during or after eating, and felling faint.", "https://ods.od.nih.gov/factsheets/VitaminC-HealthProfessional/");
        Vitamin d = new Vitamin(11,"Vitamin D", "Despite the name, vitamin D is considered a pro-hormone and not actually a vitamin. Vitamins are nutrients that cannot be created by the body and therefore must be taken in through our diet.However, vitamin D can be synthesized by our body when sunlight hits our skin. It is estimated that sensible sun exposure on bare skin for 5-10 minutes 2-3 times per week allows most people to produce sufficient vitamin D, but vitamin D breaks down quite quickly, meaning that stores can run low, especially in winter.Recent studies have suggested that a substantial percentage of the global population is vitamin D deficient. it helps regulate the amount of calcium and phosphate in the body.These nutrients are needed to keep bones, teeth and muscles healthy.A lack of vitamin D can lead to bone deformities such as rickets in children, and bone pain caused by a condition called osteomalacia in adults.", "Vitamin D has multiple roles in the body, helping to maintain the health of bones and teeth, support the health of the immune system, brain, and nervous system, regulate insulin levels and aid diabetes management, support lung function and cardiovascular health, and influence the expression of genes involved in cancer development.", "The body creates vitamin D from direct sunlight on the skin when outdoors. Vitamin D is also found in a small number of foods such as oily fish, red meat, liver, egg yolks, fortified foods", "Taking too many vitamin D supplements over a long period of time can cause too much calcium to build up in the body (hypercalcaemia). You cannot overdose on vitamin D through exposure to sunlight. But always remember to cover up or protect your skin if you're out in the sun for long periods to reduce the risk of skin damage and skin cancer.", "https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-d/");
        Vitamin e = new Vitamin(12,"Vitamin E", "Vitamin E is a fat-soluble nutrient that is available from several food sources as well as in supplement form. Some people believe that vitamin E has a positive impact on hair health, although more research is necessary to support this theory. It is also an antioxidant. This means it helps to slow down processes that damage cells. Vitamin E oil is an ingredient in many skincare products; especially those that claim to have anti-aging benefits.", "Vitamin E oil's potential benefits derive from two key features: its antioxidant properties, which could fight inflammation and slow the effects of free radicals, and its moisturizing properties. Some purported benefits of vitamin E oil is moisturizing skin, wound healing skin cancer prevention, reducing skin itching,  improvements in eczema symptoms, and reduction in psoriasis symptoms", "Vitamin E is found in plant-based oils, nuts, seeds, fruits, and vegetables", "There is no evidence of toxic effects from vitamin E found naturally in foods. Most adults who obtain more than the RDA of 22 IU daily are using multivitamins or separate vitamin E supplements that contain anywhere from 400-1000 IU daily.", "https://www.medicalnewstoday.com/articles/322836.php");
        Vitamin k = new Vitamin(13,"Vitamin K", "Vitamin K is needed for blood clotting, which means it helps wounds heal properly. It is actually a group of compounds. The most important of these compounds appears to be vitamin K1 and vitamin K2. Vitamin K1 is obtained from leafy greens and some other vegetables. Vitamin K2 is a group of compounds largely obtained from meats, cheeses, and eggs, and synthesized by bacteria.", "Vitamin K benefits the body in various ways including bone health, cognitive health, and heart health", "Good sources of vitamin K is grean leafy vegetables, vegetable oils, and cereal grains. Small amounts can also be found in meat and dairy foods.", "There's not enough evidence to know what the effects might be of taking high doses of vitamin K supplements each day.", "https://www.medicalnewstoday.com/articles/219867.php, https://www.nhs.uk/conditions/vitamins-and-minerals/vitamin-k/");
        vitaminArrayList.add(a);
        vitaminArrayList.add(b);
        vitaminArrayList.add(b2);
        vitaminArrayList.add(b3);
        vitaminArrayList.add(b5);
        vitaminArrayList.add(b6);
        vitaminArrayList.add(b7);
        vitaminArrayList.add(b9);
        vitaminArrayList.add(b12);
        vitaminArrayList.add(c);
        vitaminArrayList.add(d);
        vitaminArrayList.add(e);
        vitaminArrayList.add(k);
    }


    public ArrayList<Vitamin> getVitaminArrayList() {
        return vitaminArrayList;
    }
    public Vitamin getVitamin(int id){
        for (Vitamin v : vitaminArrayList) {
            if(v.getVid() == id){
                return v;
            }
        }
        return null;
    }
}
